module.exports = {
  trailingComma: "all",
  printWidth: 80,
  tabWidth: 2,
  importOrder: [
    "^react$",
    "^next/(.*)$",
    "<THIRD_PARTY_MODULES>",
    "^@mui/(.*)$",
    "^@/layouts/(.*)$",
    "^@/components/(.*)$",
    "^@/features/(.*)$",
    "^@/hooks/(.*)$",
    "^@/redux/(.*)$",
    "^@/themes/(.*)$",
    "^@/utils/(.*)$",
    "^[./]",
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  plugins: [require("prettier-plugin-tailwindcss")],
};
